cardsData = [
  {faceValue: "Wild", color: "none", points: 25},
  {faceValue: "Wild", color: "none", points: 25},
  {faceValue: "Wild", color: "none", points: 25},
  {faceValue: "Wild", color: "none", points: 25},
  {faceValue: "Wild", color: "none", points: 25},
  {faceValue: "Wild", color: "none", points: 25},
  {faceValue: "Wild", color: "none", points: 25},
  {faceValue: "Wild", color: "none", points: 25},
  {faceValue: "Skip", color: "none", points: 15},
  {faceValue: "Skip", color: "none", points: 15},
  {faceValue: "Skip", color: "none", points: 15},
  {faceValue: "Skip", color: "none", points: 15},
  {faceValue: "1", color: "red", points: 5},
  {faceValue: "1", color: "red", points: 5},
  {faceValue: "1", color: "blue", points: 5},
  {faceValue: "1", color: "blue", points: 5},
  {faceValue: "1", color: "green", points: 5},
  {faceValue: "1", color: "green", points: 5},
  {faceValue: "1", color: "yellow", points: 5},
  {faceValue: "1", color: "yellow", points: 5},
  {faceValue: "2", color: "red", points: 5},
  {faceValue: "2", color: "red", points: 5},
  {faceValue: "2", color: "blue", points: 5},
  {faceValue: "2", color: "blue", points: 5},
  {faceValue: "2", color: "green", points: 5},
  {faceValue: "2", color: "green", points: 5},
  {faceValue: "2", color: "yellow", points: 5},
  {faceValue: "2", color: "yellow", points: 5},
  {faceValue: "3", color: "red", points: 5},
  {faceValue: "3", color: "red", points: 5},
  {faceValue: "3", color: "blue", points: 5},
  {faceValue: "3", color: "blue", points: 5},
  {faceValue: "3", color: "green", points: 5},
  {faceValue: "3", color: "green", points: 5},
  {faceValue: "3", color: "yellow", points: 5},
  {faceValue: "3", color: "yellow", points: 5},
  {faceValue: "4", color: "red", points: 5},
  {faceValue: "4", color: "red", points: 5},
  {faceValue: "4", color: "blue", points: 5},
  {faceValue: "4", color: "blue", points: 5},
  {faceValue: "4", color: "green", points: 5},
  {faceValue: "4", color: "green", points: 5},
  {faceValue: "4", color: "yellow", points: 5},
  {faceValue: "4", color: "yellow", points: 5},
  {faceValue: "5", color: "red", points: 5},
  {faceValue: "5", color: "red", points: 5},
  {faceValue: "5", color: "blue", points: 5},
  {faceValue: "5", color: "blue", points: 5},
  {faceValue: "5", color: "green", points: 5},
  {faceValue: "5", color: "green", points: 5},
  {faceValue: "5", color: "yellow", points: 5},
  {faceValue: "5", color: "yellow", points: 5},
  {faceValue: "6", color: "red", points: 5},
  {faceValue: "6", color: "red", points: 5},
  {faceValue: "6", color: "blue", points: 5},
  {faceValue: "6", color: "blue", points: 5},
  {faceValue: "6", color: "green", points: 5},
  {faceValue: "6", color: "green", points: 5},
  {faceValue: "6", color: "yellow", points: 5},
  {faceValue: "6", color: "yellow", points: 5},
  {faceValue: "7", color: "red", points: 5},
  {faceValue: "7", color: "red", points: 5},
  {faceValue: "7", color: "blue", points: 5},
  {faceValue: "7", color: "blue", points: 5},
  {faceValue: "7", color: "green", points: 5},
  {faceValue: "7", color: "green", points: 5},
  {faceValue: "7", color: "yellow", points: 5},
  {faceValue: "7", color: "yellow", points: 5},
  {faceValue: "8", color: "red", points: 5},
  {faceValue: "8", color: "red", points: 5},
  {faceValue: "8", color: "blue", points: 5},
  {faceValue: "8", color: "blue", points: 5},
  {faceValue: "8", color: "green", points: 5},
  {faceValue: "8", color: "green", points: 5},
  {faceValue: "8", color: "yellow", points: 5},
  {faceValue: "8", color: "yellow", points: 5},
  {faceValue: "9", color: "red", points: 5},
  {faceValue: "9", color: "red", points: 5},
  {faceValue: "9", color: "blue", points: 5},
  {faceValue: "9", color: "blue", points: 5},
  {faceValue: "9", color: "green", points: 5},
  {faceValue: "9", color: "green", points: 5},
  {faceValue: "9", color: "yellow", points: 5},
  {faceValue: "9", color: "yellow", points: 5},
  {faceValue: "10", color: "red", points: 10},
  {faceValue: "10", color: "red", points: 10},
  {faceValue: "10", color: "blue", points: 10},
  {faceValue: "10", color: "blue", points: 10},
  {faceValue: "10", color: "green", points: 10},
  {faceValue: "10", color: "green", points: 10},
  {faceValue: "10", color: "yellow", points: 10},
  {faceValue: "10", color: "yellow", points: 10},
  {faceValue: "11", color: "red", points: 10},
  {faceValue: "11", color: "red", points: 10},
  {faceValue: "11", color: "blue", points: 10},
  {faceValue: "11", color: "blue", points: 10},
  {faceValue: "11", color: "green", points: 10},
  {faceValue: "11", color: "green", points: 10},
  {faceValue: "11", color: "yellow", points: 10},
  {faceValue: "11", color: "yellow", points: 10},
  {faceValue: "12", color: "red", points: 10},
  {faceValue: "12", color: "red", points: 10},
  {faceValue: "12", color: "blue", points: 10},
  {faceValue: "12", color: "blue", points: 10},
  {faceValue: "12", color: "green", points: 10},
  {faceValue: "12", color: "green", points: 10},
  {faceValue: "12", color: "yellow", points: 10},
  {faceValue: "12", color: "yellow", points: 10}
]

function DeckBuilder(){
  this.deckInfo = deckInfo
}

function DeckBuilder.prototype.buildDeck(){
  var cardsForDeck, i, j = [[], 0, this.deckInfo.length]
  for (i; i < j; i++) {
    cardsForDeck.push(new Card(this.deckInfo[i]));
  }
  return new Deck(cardsForDeck);
}